#!/bin/bash

# Turn verbose output OFF so we don't echo the output of the secrets file
set +ev

if [ -f /dev/shm/redshift-secondary-env ]; then
  source /dev/shm/redshift-secondary-env
else
echo "/dev/shm/redshift-secondary-env not found. Check your Clortho config."
fi

# Turn verbose output back ON for troubleshooting
set -ev

exec /sbin/setuser socrata java -agentlib:jdwp='transport=dt_socket,server=y,suspend=n,address=*:5005' -Dquarkus.profile=docker -Djava.util.logging.manager=org.jboss.logmanager.LogManager -jar /home/socrata/quarkus-run.jar
