version:
  version: 5.2
redshift:
aws:
  region: ${AWS_DEFAULT_REGION}
  accessKey: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}
zookeeper:
  ensemble: ${ZK_ENSEMBLE}
  baseSleepTimeMs: ${ZK_BASE_SLEEP_TIME_MS}
  maxSleepTimeMs: ${ZK_MAX_SLEEP_TIME_MS}
  maxRetries: ${ZK_MAX_RETRIES}
quarkus:
  test:
    hang-detection-timeout:
  log:
    level: INFO
  datasource:
    #   meta is our metadata store, our postgres
    meta:
      db-kind: h2
      username: meta
      jdbc:
        url: jdbc:h2:mem:meta
        max-size: 11
    #   store is our data store, our redshift
    store:
      db-kind: other
      username: masteruser
      password: ${REDSHIFT_PASSWORD}
      jdbc:
        driver: com.amazon.redshift.jdbc.Driver
        url: jdbc:redshift://redshiftinstance-wtckbqvktove.ck5lkhdheomu.us-west-2.redshift.amazonaws.com:5439/dev?reWriteBatchedInserts=true&reWriteBatchedInsertsSize=1048576 # Must be power of 2. Max rewrite insert size. We will flush buffer manually long before this.
