version:
  version: 5.2
redshift:
quarkus:
  log:
    level: INFO
  datasource:
#   meta is our metadata store, our postgres
    meta:
      db-kind: h2
      username: meta
      jdbc:
        url: jdbc:h2:mem:meta
        max-size: 11
#   store is our data store, our redshift
    store:
      db-kind: other
      username: masteruser
      password: ${REDSHIFT_PASSWORD}
      jdbc:
        driver: com.amazon.redshift.jdbc.Driver
        url: jdbc:redshift://redshiftinstance-wtckbqvktove.ck5lkhdheomu.us-west-2.redshift.amazonaws.com:5439/dev
